name: bus_route_finder
description: "A Flutter project for bus route finding with map integration"
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Map & Location
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^10.0.1
  geocoding: ^2.1.0
  location: ^5.0.1
  flutter_map_marker_cluster: ^1.1.0   # downgraded for latlong2 ^0.8.x

  # UI & Animations
  google_fonts: ^4.0.4
  animate_do: ^3.0.2
  lottie: ^2.6.0
  provider: ^6.0.5

  # Networking & Data
  http: ^0.13.5
  mongo_dart: ^0.10.1+1
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/d.jpg
    - lib/assets/images/b.jpg
    - lib/assets/images/sp.jpg
    - lib/assets/images/app_logo.jpg
    - lib/assets/images/app_logo.png
    - lib/assets/images/splash_screen_bg.jpg
    - lib/assets/images/routescreenbg.jpg
    - lib/assets/images/pattern.png
    - lib/assets/images/re.png

# Flutter Launcher Icons Configuration
flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/images/app_logo.png
